jobs:
  - id: 1
    name: Проверка состояния оборудования системы
    schedule: "0 0/10 * 1/1 * ?"
    description: Проверить статус всего оборудования в каждой подключенной системе
    method: CheckDevicesState